jobs:
    include:
        language: python
        python:
            - "3.6"
            - "3.7"
            - "3.8"

        before_script:
            - bash install.sh

        # command to run tests
        script:
            - python -m unittest password_validator/test__main__.py
